camera360: {
  front: {
    sub_topics: {
      front_lens: "/camera360/front_lens/front_projection/image_rect",
      rear_lens: ""
    },
    pub_topics: ,
    stitch_calib_file: "",
    bev_calib_file: "",
    bev_pose: [],
  },

  rear: {
    sub_topics: {
      front_lens: "",
      rear_lens: "/camera360/rear_lens/front_projection/image_rect"
    },
    pub_topics: ,
    stitch_calib_file: "",
    bev_calib_file: "",
    bev_pose: [],
  },

  left: {
    topics: {
      front_lens: "/camera360/front_lens/left_projection/image_rect",
      rear_lens: "/camera360/rear_lens/right_projection/image_rect"
    },
    pub_topics: ,
    stitch_calib_file: "$(find camera360_perception)/configs/stitch_left.yaml",
    bev_calib_file: "",
    bev_pose: [],
  },

  right: {
    topics: {
      front_lens: "/camera360/front_lens/right_projection/image_rect",
      rear_lens: "/camera360/rear_lens/left_projection/image_rect"
    },
    pub_topics: ,
    stitch_calib_file: "$(find camera360_perception)/configs/stitch_right.yaml",
    bev_calib_file: "",
    bev_pose: [],
  },
}